run:
  timeout: 5m

linters-settings:
  errcheck:
    checks:
      - blank-assignments
      - no-implicit-errcheck
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters: [errcheck]
