{{- if include "alertlens.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertlens.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alertlens.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.alertlens.adminPassword | default "" | quote }}
  github-token: {{ .Values.alertlens.gitops.github.token | default "" | quote }}
  gitlab-token: {{ .Values.alertlens.gitops.gitlab.token | default "" | quote }}
{{- end }}
