name: Release & Test
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.22.2' }
      - name: Run E2E Tests
        run: make test-e2e
  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'release:')
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
